added Log
IgorBoyarshin/Hangman pull request #1
Opened 2018-10-29 17:40 UTC by AnnaDoroshenko

Check this out

2018-10-29 17:53 UTC, IgorBoyarshin requested changes
Fix the specified things

2018-10-29 17:53 UTC, IgorBoyarshin commented on src/Log.cpp
> +Log::Log(OutputLevel outputLevel) : m_ClassName(""), m_FuncName("") {
```suggestion
Log::Log(OutputLevel outputLevel) : m_ClassName(""), m_FuncName(""), m_LogLevel(LogLevel::Info) {
```

2018-10-29 17:53 UTC, IgorBoyarshin commented on src/Log.cpp
> +Log::Log(OutputLevel outputLevel) : m_ClassName(""), m_FuncName("") {
Also could move the body of the constructor here as well

2018-10-29 17:53 UTC, IgorBoyarshin commented on src/main.cpp
> +    std::cout << log.setLevel(Log::LogLevel::Info) << "test" << std::endl;
Don't want to deal with std::cout. Make Log self-sufficient: 
`log.setLevel(...) << ...`

2018-10-31 11:43 UTC, AnnaDoroshenko commented
Finished. Check corrections out.

2018-10-31 11:44 UTC, IgorBoyarshin approved these changes

2018-10-31 11:47 UTC, merged